# Generated by Django 2.0 on 2022-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_feedback_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='status',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='userregister_model',
            name='status',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
